Repository SQLutions-FATEC/API-3-Semestre-Frontend, pull requests merged in 2025-03, with the labels that each got.

#1 build(organizacao-inicial): Organiza pastas e instala sass
  front/.env.example
  front/.gitignore
  front/.nvmrc
  front/README.md
  front/package-lock.json
  front/package.json
  front/src/components/Button/AtButton.vue
  front/src/components/Input/AtInput.vue
  front/src/main.js
  front/src/mock/routes/loginRoutes.js
  front/src/mock/seeds/userSeeds.js
  front/src/pages/Login/Login.vue
  front/src/style.css
  front/src/styles/__border-radius.scss
  front/src/styles/__breakpoints.scss
  front/src/styles/__colors.scss
  front/src/styles/__fonts.scss
  front/src/styles/__spacers.scss
  front/src/styles/main.scss
  front/src/utils/services/api.js
  front/src/utils/services/login.js
  front/src/utils/validations/email.js
  front/vite.config.js
Labels: enhancement

#2 build(axios-eslint): Adiciona axios e eslint no projeto
  front/.eslintrc.js
  front/.prettierrc
  front/README.md
  front/package-lock.json
  front/package.json
  front/src/App.vue
  front/src/components/HelloWorld.vue
  front/src/main.js
  front/src/utils/services/api.js
  front/src/utils/services/login.js
Labels: enhancement

#3 build(vue-router): Adiciona vue router no projeto
  front/README.md
  front/package-lock.json
  front/package.json
  front/src/App.vue
  front/src/main.js
  front/src/pages/Login/Login.vue
  front/src/router/router.js
Labels: enhancement

#5 build(mirage): Instala dependência de mock e faz funcionar
  front/README.md
  front/mirage.config.js
  front/package-lock.json
  front/package.json
  front/src/main.js
  front/src/mock/routes/loginRoutes.js
  front/src/mock/seeds/userSeeds.js
  front/src/mock/utils.js
  front/src/router/router.js
Labels: enhancement

#6 chore(pastas): reorganiza a estrutura
  .env.example
  .eslintrc.js
  .gitignore
  .nvmrc
  .prettierrc
  .vscode/settings.json
  README.md
  front/.vscode/extensions.json
  front/README.md
  index.html
  mirage.config.js
  package-lock.json
  package.json
  public/vite.svg
  src/App.vue
  src/assets/vue.svg
  src/components/Button/AtButton.vue
  src/components/HelloWorld.vue
  src/components/Input/AtInput.vue
  src/main.js
  src/mock/routes/loginRoutes.js
  src/mock/seeds/userSeeds.js
  src/mock/utils.js
  src/pages/Login/Login.vue
  src/router/router.js
  src/stores/loginStore.js
  src/styles/__border-radius.scss
  src/styles/__breakpoints.scss
  src/styles/__colors.scss
  src/styles/__fonts.scss
  src/styles/__spacers.scss
  src/styles/main.scss
  src/utils/services/api.js
  src/utils/services/login.js
  src/utils/validations/email.js
  vite.config.js
Labels: bug, enhancement

#7 build(ant-design): instala dependencia e faz funcionar
  README.md
  package-lock.json
  package.json
  src/App.vue
  src/main.js
  src/pages/Login/Login.vue
  src/services/api.js
  src/services/login.js
Labels: enhancement

#8 feat(company-screen): Cria tela de cadastro de empresa
  index.html
  public/altave.svg
  public/vite.svg
  src/App.vue
  src/assets/vue.svg
  src/components/HelloWorld.vue
  src/components/SideBar.vue
  src/components/TopBar.vue
  src/main.js
  src/pages/Company/Company.vue
  src/pages/Employee/Employee.vue
  src/pages/Home/Home.vue
  src/router/router.js
  src/styles/__border-radius.module.scss
  src/styles/__border-radius.scss
  src/styles/__colors.module.scss
  src/styles/__fonts.module.scss
  src/styles/__spacers.module.scss
  src/styles/__spacers.scss
  src/styles/main.scss
  vite.config.js
Labels: enhancement

#9 feat(company-screen): Cria lógica para cadastro de empresa
  mirage.config.js
  package-lock.json
  package.json
  src/components/Input/AtInput.vue
  src/components/Input/AtNumberInput.vue
  src/mock/routes/companyRoutes.js
  src/mock/routes/loginRoutes.js
  src/mock/seeds/companySeeds.js
  src/mock/seeds/userSeeds.js
  src/pages/Company/Company.vue
  src/services/company.js
  src/services/login.js
  src/styles/main.scss
  vite.config.js
Labels: enhancement

#11 feat(edit-company): Criação da edição da empresa
  src/App.vue
  src/components/Input/AtInput.vue
  src/components/SideBar.vue
  src/mock/routes/companyRoutes.js
  src/pages/Company/Company.vue
  src/pages/Home/Home.vue
  src/router/router.js
  src/services/company.js
Labels: enhancement

#13 feat(axios)/Integra com backend
  .env.example
  package.json
  src/main.js
  src/services/api.js
  vite.config.js
Labels: enhancement

#10 Scrum 1/criacao funcionario
  src/pages/Employee/Employee.vue
  vite.config.js
Labels: enhancement

#14 Scrum 1/mock funcionario
  src/pages/Employee/Employee.vue
  vite.config.js
Labels: enhancement

#12 Scrum 5/visualizacao edicao funcionario
  src/components/SideBar.vue
  src/pages/Employee/EmployeeEdit.vue
  src/router/router.js
Labels: enhancement

#15 hotfix/Corrige o script para subir projeto usando mock
  mirage.config.js
  package-lock.json
  package.json
Labels: bug

#17 SCRUM-25/Cria tabela de movimentação
  .env.example
  README.md
  mirage.config.js
  src/mock/routes/clockInOutRoutes.js
  src/mock/seeds/clockInOutSeeds.js
  src/pages/Home/Home.vue
  src/services/clockInOut.js
Labels: enhancement

#16 Scrum 1/mock funcionario
  mirage.config.js
  src/components/SideBar.vue
  src/mock/routes/employeeRoutes.js
  src/mock/seeds/employeeSeeds.js
  src/pages/Employee/Employee.vue
  src/services/employee.js
Labels: enhancement
