Repository SQLutions-FATEC/API-3-Semestre-Frontend, pull requests merged in 2025-05, with the labels that each got.

#44 SCRUM-90/Cria acesso para tela de dashboard
  package-lock.json
  package.json
  src/components/SideBar.vue
  src/pages/Dashboard/Dashboard.vue
  src/router/router.js
Labels: enhancement

#43 SCRUM-X/Instruções de build do frontend
  README.md
Labels: documentation

#41 Scrum 80/pin header filters to screens
  src/components/Headers/HomeHeader.vue
  src/pages/Home/Home.vue
Labels: bug, enhancement

#42 SCRUM-89/Adapta tabela de movimentacoes
  src/components/Modals/EditClockInModal.vue
  src/mock/routes/clockInOutRoutes.js
  src/mock/seeds/clockInOutSeeds.js
  src/mock/seeds/employeeSeeds.js
  src/pages/Home/Home.vue
  src/styles/__colors.module.scss
  src/styles/antd-overrides.scss
Labels: enhancement

#39 SCRUM-77/Refatora visual dos contratos
  .gitignore
  mirage.config.js
  src/App.vue
  src/components/Button/ExcelExportButton.vue
  src/components/Contracts/ActiveContract.vue
  src/components/Contracts/Contracts.vue
  src/components/Contracts/InactiveContracts.vue
  src/components/Modals/ContractModal.vue
  src/components/Modals/InactivateContractModal.vue
  src/components/Modals/RoleModal.vue
  src/components/SideBar.vue
  src/components/TopBar.vue
  src/mock/routes/contractRoutes.js
  src/mock/routes/employeeRoutes.js
  src/mock/seeds/contractSeeds.js
  src/mock/seeds/employeeSeeds.js
  src/pages/Company/Company.vue
  src/pages/Employee/Employee.vue
  src/pages/Home/Home.vue
  src/services/contracts.js
  src/services/photo.js
  src/services/role.js
  src/styles/__colors.module.scss
  src/styles/antd-overrides.scss
Labels: enhancement

#45 SCRUM-91/Gráficos parte - 1
  index.html
  mirage.config.js
  package-lock.json
  package.json
  src/components/DailyRegisters.vue
  src/components/Graphs/GraphEmployeesByGender.vue
  src/components/Graphs/GraphHoursWorkedByRole.vue
  src/components/Modals/ContractModal.vue
  src/components/SideBar.vue
  src/mock/routes/dashboardRoutes.js
  src/mock/seeds/dashboardSeeds.js
  src/pages/Dashboard/Dashboard.vue
  src/services/dashboard.js
  src/styles/__colors.module.scss
  src/styles/__fonts.module.scss
  src/styles/main.scss
  src/utils/index.js
Labels: enhancement

#47 SCRUM-92/Gráficos parte 2
  src/components/Contracts/ActiveContract.vue
  src/components/Contracts/Contracts.vue
  src/components/DashboardAlerts/ContractsToExpire.vue
  src/components/DashboardAlerts/WithoutMatchRegisters.vue
  src/components/Graphs/GraphEmployeesByGender.vue
  src/components/Graphs/GraphHoursWorkedByRole.vue
  src/mock/routes/dashboardRoutes.js
  src/mock/seeds/clockInOutSeeds.js
  src/mock/seeds/contractSeeds.js
  src/pages/Dashboard/Dashboard.vue
  src/services/dashboard.js
  src/utils/index.js
Labels: enhancement

#49 SCRUM-85/Cria tabela de funcionários
  src/components/Contracts/ActiveContract.vue
  src/components/Contracts/Contracts.vue
  src/components/Contracts/InactiveContracts.vue
  src/components/DashboardAlerts/ContractsToExpire.vue
  src/components/DashboardAlerts/WithoutMatchRegisters.vue
  src/components/Headers/EmployeeHeader.vue
  src/components/Headers/HomeHeader.vue
  src/components/Modals/EditClockInModal.vue
  src/components/Modals/EmployeeModal.vue
  src/components/SideBar.vue
  src/mock/routes/employeeRoutes.js
  src/pages/Employee/EmployeeHome.vue
  src/pages/Home/Home.vue
  src/router/router.js
  src/styles/antd-overrides.scss
  src/utils/index.js
Labels: enhancement

#50 Hotfix/Manda paginação para backend
  src/services/employee.js
Labels: bug

#48 SCRUM 81/Cria um botão para exportar todos os registros
  src/components/Button/ExcelExportButton.vue
  src/services/clockInOut.js
Labels: enhancement

#46 feat(79): inserts label style globally
  src/App.vue
  src/components/HomeFilters.vue
  src/components/Input/AtNumberInput.vue
  src/components/Modals/CompanyModal.vue
  src/components/Modals/ContractModal.vue
  src/components/Modals/EditClockInModal.vue
  src/components/Modals/EmployeeModal.vue
  src/main.js
  src/pages/Company/Company.vue
  src/pages/Home/Home.vue
  src/styles/main.scss
Labels: enhancement

#54 SCRUM-79/Correções de bug, parâmetros e estilos
  src/App.vue
  src/components/HomeFilters.vue
  src/components/Input/AtNumberInput.vue
  src/components/Modals/CompanyModal.vue
  src/components/Modals/ContractModal.vue
  src/components/Modals/EditClockInModal.vue
  src/components/Modals/EmployeeModal.vue
  src/components/Modals/RoleModal.vue
  src/main.js
  src/pages/Company/Company.vue
  src/pages/Company/CompanyHome.vue
  src/pages/Dashboard/Dashboard.vue
  src/pages/Employee/EmployeeHome.vue
  src/styles/main.scss
Labels: bug

#55 SCRUM-102: Melhorias sugeridas pela professora
  src/components/DailyRegisters.vue
  src/components/DashboardAlerts/ContractsToExpire.vue
  src/components/DashboardAlerts/WithoutMatchRegisters.vue
  src/components/Graphs/GraphEmployeesByGender.vue
  src/components/Graphs/GraphEmployeesByShift.vue
  src/components/Graphs/GraphHoursWorkedByRole.vue
  src/components/Headers/CompanyHeader.vue
  src/components/Headers/EmployeeHeader.vue
  src/components/HomeFilters.vue
  src/pages/Company/Company.vue
  src/pages/Company/CompanyHome.vue
  src/pages/Dashboard/Dashboard.vue
  src/pages/Employee/EmployeeHome.vue
  src/services/dashboard.js
Labels: enhancement
